# Generated by Django 3.2.4 on 2021-07-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('join_date', models.DateTimeField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000, null=True)),
                ('task_pic', models.ImageField(upload_to='media/task_image')),
                ('create_time_stamp', models.DateTimeField(default='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.user')),
            ],
        ),
    ]
