# Generated by Django 3.2.4 on 2021-07-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='uid',
        ),
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task1.user'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='create_time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tid',
            field=models.IntegerField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
