# Generated by Django 3.2.4 on 2021-07-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_auto_20210722_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='username',
            new_name='uid_id',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
