# Generated by Django 3.2.4 on 2021-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SINO', models.IntegerField()),
                ('title', models.CharField(default='', max_length=20)),
                ('parentID', models.IntegerField(null=True)),
            ],
        ),
    ]
