# Generated by Django 3.2.4 on 2021-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktwo',
            name='parentID',
            field=models.IntegerField(blank=True),
        ),
    ]
